### ISSUE TITLE
Latest release 0.4.0 breaks

### ISSUE THREAD

**Issue by StarpTech** [bufbuild/connect-query#70] opened 2023-07-26 15:53 UTC
After upgrading to `0.4.0` we see the following error

```
[unknown] To use Connect, you must provide a `Transport`: a simple object that handles `unary` and `stream` requests. `Transport` objects can easily be created by using `@bufbuild/connect-web`'s exports `createConnectTransport` and `createGrpcWebTransport`. see: https://connect.build/docs/web/getting-started for more
```

Revert to `0.3.0` fix the issue.

Versions:
```
    "@bufbuild/connect": "^0.12.0",
    "@bufbuild/connect-query": "^0.4.0",
    "@bufbuild/connect-web": "^0.12.0",
    "@bufbuild/protobuf": "^1.3.0",
```

Used in Next.js

**Comment by StarpTech** [comment] 2023-07-27 13:32
Hi @timostamm according to your deps you don't use Next.js. Please retry with Next.js. As a User, I can't influence how Next.js resolve modules.

Besides that, you also don't use the same version as I reported in the issue. Nonetheless, I tried your matrix in Next.js but run into the same issue.

**Comment by timostamm** [comment] 2023-07-27 17:39
> Please retry with Next.js.

I just ran the following commands (using the default answers in the setup):

```bash
npx create-next-app@latest
cd my-app
npm i @bufbuild/connect-query @bufbuild/connect-web @tanstack/react-query
```

This gives me:
```bash
$ npm ls
├── @bufbuild/connect-query@0.4.0
├── @bufbuild/connect-web@0.12.0
├── @tanstack/react-query@4.32.0
├── @types/node@20.4.5
├── @types/react-dom@18.2.7
├── @types/react@18.2.17
├── next@13.4.12
├── react-dom@18.2.0
├── react@18.2.0
└── typescript@5.1.6
```

Then I copied the minimal parts from the example linked above, set "use client", and ran `npm run dev`. 
As a result, I'm seeing a web page that makes a successful request to ElizaService/Say without errors.

I noticed that your profile page says you are the Tech Lead of wundergraph. Your [issue template](https://github.com/wundergraph/wundergraph/blob/9f08c96f3909cdc6194dbef638d8cef71a4ffd04/.github/ISSUE_TEMPLATE/issue.yml) says:

> The first step of us working on addressing this issue is that we validate the issue by reproducing it.
It's important that we can reproduce the issue on an environment that is not your computer or server environment.

I'm sure you understand that this principle that applies to pretty much all open source projects. With the information you provided, it is not possible to reproduce the issue, and it is therefore impossible to fix. Ideally, you provide a _minimal_ reproducible example. 

Same as your open source projects, we are also open to pull requests that demonstrate an issue and resolve it.

Closing this, but - and I sincerely mean that - feel free to reopen with detailed information.

**Closed by timostamm** 2023-07-27 17:39 UTC

**Comment by StarpTech** [comment] 2023-07-27 18:03
The main distinction between our template and yours is that we have one. It's quite common to write an issue in a free form if no specific requirements are defined. Truthfully, during its creation, I didn't consider it much and provided only minimal information. However, I'm more than willing to offer additional details if necessary. There's no reason to close issues prematurely or take things personally. Such reactions often diminish the enjoyment of participating in open-source projects.

**Comment by StarpTech** [comment] 2023-08-20 22:12
**Quick update:** We were able to fix it by ensuring that our auto-generated "connect-query" files are transpiled with TypeScript option ` "module": "ESNext"`. Otherwise, Next.js loads the ESM version and the generated files the CJS version.

Is there any documentation on how to prepare a buf proto library for consumption? I couldn't find one.

**Comment by smaye81** [comment] 2023-08-22 19:19
Hi @StarpTech. There isn't a document for this for connect-query because this isn't specific to connect-query and is instead a problem with the ecosystem. We actually have plans on our roadmap to try to solve this across our packages, but we want to be careful not to break users who may be using outdated bundlers. Once we have a good path forward, we will provide documentation for how this is handled.
